-- 02_metadata_and_index.sql
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='LIBRARIES' AND COLUMN_NAME='LOCATION';

INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) VALUES (
  'LIBRARIES', 'LOCATION',
  MDSYS.SDO_DIM_ARRAY(
    MDSYS.SDO_DIM_ELEMENT('LONG', -180, 180, 0.0001),
    MDSYS.SDO_DIM_ELEMENT('LAT',  -90,  90,  0.0001)
  ),
  4326
);

BEGIN EXECUTE IMMEDIATE 'DROP INDEX LIBRARIES_SPATIAL_IDX'; EXCEPTION WHEN OTHERS THEN NULL; END; /
CREATE INDEX LIBRARIES_SPATIAL_IDX ON LIBRARIES(LOCATION)
  INDEXTYPE IS MDSYS.SPATIAL_INDEX
  PARAMETERS('layer_gtype=POINT');
