-- 04_borrow_seed.sql
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_BORROW'; EXCEPTION WHEN OTHERS THEN NULL; END; /
CREATE SEQUENCE SEQ_BORROW START WITH 10001 INCREMENT BY 1;

BEGIN
  INSERT INTO USERS (user_id, student_id, name, password_hash, home_lib_id)
  VALUES (1, '20250001', '张三', 'dummy-hash', 1);
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
COMMIT;
